"""Ghost Learner — analyzes completed trades and generates self-calibration adjustments.

After each backtest run, the learner:
  1. Groups trades by instrument, direction, kill zone, regime
  2. Calculates win rate, avg R:R, expectancy per group
  3. Generates per-instrument and per-session adjustments
  4. Persists learnings to JSON for the next run
  5. Multi-pass learning: iterates backtest N times, improving each pass
  6. Tracks performance history across runs for improvement visibility
"""
import json
import os
import copy
import structlog
import numpy as np
from dataclasses import dataclass, field, asdict
from typing import List, Dict, Optional, Any
from collections import defaultdict
from datetime import datetime, timezone

logger = structlog.get_logger()

# Default path for persisted learnings
DEFAULT_LEARNINGS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "config", "learnings.json",
)


@dataclass
class TradeGroupStats:
    """Statistics for a group of trades."""
    group_key: str
    total_trades: int = 0
    wins: int = 0
    losses: int = 0
    win_rate: float = 0.0
    avg_rr: float = 0.0
    expectancy: float = 0.0
    total_pnl: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    stop_hit_but_tp_reached: int = 0  # Trades where stop hit but price later went to TP


@dataclass
class CalibrationAdjustments:
    """Adjustments generated by the learner."""
    instruments: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    sessions: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    global_adjustments: Dict[str, Any] = field(default_factory=dict)
    pass_number: int = 0
    source_win_rate: float = 0.0
    source_trades: int = 0


class GhostLearner:
    """Analyzes backtest trades and generates calibration adjustments.

    Usage:
        learner = GhostLearner()
        adjustments = learner.analyze(trades, instrument="MNQ")
        learner.save()

        # Multi-pass:
        best_config = learner.learn_and_improve(bars, instrument, passes=5)
    """

    def __init__(self, learnings_path: str = DEFAULT_LEARNINGS_PATH):
        self.learnings_path = learnings_path
        self.adjustments = CalibrationAdjustments()
        self._trade_groups: Dict[str, TradeGroupStats] = {}
        self._log = logger.bind(component="GhostLearner")
        self._performance_history: List[Dict[str, Any]] = []

    def load(self) -> CalibrationAdjustments:
        """Load persisted learnings from JSON, including performance history."""
        if os.path.exists(self.learnings_path):
            try:
                with open(self.learnings_path, "r") as f:
                    data = json.load(f)
                self.adjustments = CalibrationAdjustments(
                    instruments=data.get("instruments", {}),
                    sessions=data.get("sessions", {}),
                    global_adjustments=data.get("global_adjustments", {}),
                    pass_number=data.get("pass_number", 0),
                    source_win_rate=data.get("source_win_rate", 0.0),
                    source_trades=data.get("source_trades", 0),
                )
                self._performance_history = data.get("performance_history", [])
                self._log.info("learnings_loaded", path=self.learnings_path,
                               instruments=len(self.adjustments.instruments),
                               history_entries=len(self._performance_history))
            except (json.JSONDecodeError, Exception) as e:
                self._log.warning("learnings_load_failed", error=str(e))
                self.adjustments = CalibrationAdjustments()
                self._performance_history = []
        return self.adjustments

    def save(self) -> None:
        """Persist learnings to JSON, including performance history."""
        os.makedirs(os.path.dirname(self.learnings_path), exist_ok=True)
        data = {
            "instruments": self.adjustments.instruments,
            "sessions": self.adjustments.sessions,
            "global_adjustments": self.adjustments.global_adjustments,
            "pass_number": self.adjustments.pass_number,
            "source_win_rate": self.adjustments.source_win_rate,
            "source_trades": self.adjustments.source_trades,
            "performance_history": self._performance_history,
        }
        with open(self.learnings_path, "w") as f:
            json.dump(data, f, indent=2)
        self._log.info("learnings_saved", path=self.learnings_path,
                       history_entries=len(self._performance_history))

    def record_run(self, instrument: str, result, config=None) -> None:
        """Record a backtest run's results to performance history.

        Args:
            instrument: Instrument symbol.
            result: BacktestResult from a completed run.
            config: Optional BacktestConfig used for the run.
        """
        entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "instrument": instrument,
            "total_trades": result.total_trades,
            "winning_trades": result.winning_trades,
            "losing_trades": result.losing_trades,
            "win_rate": round(result.win_rate, 4),
            "total_pnl": round(result.total_pnl, 2),
            "sharpe_ratio": round(result.sharpe_ratio, 3),
            "profit_factor": round(result.profit_factor, 3),
            "max_drawdown": round(result.max_drawdown, 2),
            "final_balance": round(result.final_balance, 2),
        }
        if config is not None:
            entry["config_snapshot"] = {
                "min_risk_ticks": config.min_risk_ticks,
                "stop_multiplier": round(config.stop_multiplier, 2),
                "tp1_ratio": round(config.tp1_ratio, 2),
                "confluence_minimum": round(config.confluence_minimum, 2),
                "tqs_minimum": config.tqs_minimum,
                "loss_cooloff_bars": config.loss_cooloff_bars,
            }
        self._performance_history.append(entry)
        self._log.info("run_recorded", instrument=instrument,
                       win_rate=entry["win_rate"],
                       total_pnl=entry["total_pnl"],
                       history_size=len(self._performance_history))

    def apply_learnings_to_config(self, config, instrument: str) -> None:
        """Apply persisted per-instrument optimal parameters to a config.

        Reads the instrument adjustments from the loaded learnings and applies
        them to the config object in-place.

        Args:
            config: BacktestConfig to modify.
            instrument: Instrument symbol.
        """
        adj = self.adjustments.instruments.get(instrument, {})
        if not adj:
            return

        # Apply stop multiplier if learned
        if "stop_multiplier" in adj:
            config.stop_multiplier = adj["stop_multiplier"]
            self._log.info("learnings_applied", instrument=instrument,
                           param="stop_multiplier", value=adj["stop_multiplier"])

        # Apply TQS bonus via instrument_overrides
        if "tqs_bonus" in adj:
            if config.instrument_overrides is None:
                config.instrument_overrides = {}
            if instrument not in config.instrument_overrides:
                config.instrument_overrides[instrument] = {}
            config.instrument_overrides[instrument]["tqs_bonus"] = adj["tqs_bonus"]

        # Apply blocked instruments if regime analysis says to skip
        blocked_regimes = adj.get("blocked_regimes", [])
        if blocked_regimes:
            self._log.info("learnings_applied", instrument=instrument,
                           param="blocked_regimes", value=blocked_regimes)

    def get_performance_history(self, instrument: Optional[str] = None) -> List[Dict[str, Any]]:
        """Return performance history, optionally filtered by instrument."""
        if instrument is None:
            return list(self._performance_history)
        return [e for e in self._performance_history if e.get("instrument") == instrument]

    def analyze(self, trades: list, instrument: str = "") -> CalibrationAdjustments:
        """Analyze completed trades and generate calibration adjustments.

        Args:
            trades: List of BacktestTrade objects from a backtest run.
            instrument: Optional instrument filter.

        Returns:
            CalibrationAdjustments with per-instrument and per-session tweaks.
        """
        if not trades:
            return self.adjustments

        # Group trades
        groups = self._group_trades(trades)
        self._trade_groups = groups

        # Calculate overall stats
        total = len(trades)
        wins = sum(1 for t in trades if t.pnl > 0)
        overall_wr = wins / total if total > 0 else 0.0

        self.adjustments.source_win_rate = overall_wr
        self.adjustments.source_trades = total

        # Generate per-instrument adjustments
        self._generate_instrument_adjustments(trades, groups)

        # Generate per-session adjustments
        self._generate_session_adjustments(trades, groups)

        # Generate global adjustments
        self._generate_global_adjustments(trades)

        self._log.info(
            "analysis_complete",
            total_trades=total,
            win_rate=round(overall_wr * 100, 1),
            groups=len(groups),
        )

        return self.adjustments

    def _group_trades(self, trades: list) -> Dict[str, TradeGroupStats]:
        """Group trades by instrument, direction, kill zone, regime."""
        groups: Dict[str, TradeGroupStats] = {}

        # Group by multiple dimensions
        for trade in trades:
            # Instrument group
            inst_key = f"inst:{trade.instrument}"
            self._add_to_group(groups, inst_key, trade)

            # Direction group
            dir_key = f"dir:{trade.instrument}:{trade.direction}"
            self._add_to_group(groups, dir_key, trade)

            # Kill zone group
            kz = getattr(trade, "kill_zone", "") or ""
            if kz:
                kz_key = f"kz:{kz}"
                self._add_to_group(groups, kz_key, trade)

            # Regime group
            regime = getattr(trade, "regime_label", "") or ""
            if regime:
                regime_key = f"regime:{regime}"
                self._add_to_group(groups, regime_key, trade)

            # Combined: instrument + regime
            if regime:
                ir_key = f"inst_regime:{trade.instrument}:{regime}"
                self._add_to_group(groups, ir_key, trade)

        # Finalize stats
        for g in groups.values():
            if g.total_trades > 0:
                g.win_rate = g.wins / g.total_trades
                g.expectancy = g.total_pnl / g.total_trades

        return groups

    def _add_to_group(self, groups: dict, key: str, trade) -> None:
        """Add a trade to a group, updating running stats."""
        if key not in groups:
            groups[key] = TradeGroupStats(group_key=key)
        g = groups[key]
        g.total_trades += 1
        g.total_pnl += trade.pnl
        if trade.pnl > 0:
            g.wins += 1
            if g.avg_win == 0:
                g.avg_win = trade.pnl
            else:
                g.avg_win = (g.avg_win * (g.wins - 1) + trade.pnl) / g.wins
        else:
            g.losses += 1
            if g.avg_loss == 0:
                g.avg_loss = trade.pnl
            else:
                g.avg_loss = (g.avg_loss * (g.losses - 1) + trade.pnl) / g.losses

        # Compute R:R if we have avg_win and avg_loss
        if g.avg_loss != 0:
            g.avg_rr = abs(g.avg_win / g.avg_loss) if g.avg_loss != 0 else 0.0

    def _generate_instrument_adjustments(self, trades: list, groups: dict) -> None:
        """Generate per-instrument adjustments based on trade group analysis."""
        instruments = set(t.instrument for t in trades)

        for inst in instruments:
            inst_key = f"inst:{inst}"
            if inst_key not in groups:
                continue

            g = groups[inst_key]
            adj = self.adjustments.instruments.get(inst, {})

            # Rule 1: If instrument has <40% win rate over 10+ trades, increase TQS minimum by 5
            if g.total_trades >= 10 and g.win_rate < 0.40:
                current_bonus = adj.get("tqs_bonus", 0)
                adj["tqs_bonus"] = current_bonus + 5
                self._log.info("learner.tqs_increase",
                               instrument=inst, win_rate=round(g.win_rate, 3),
                               new_tqs_bonus=adj["tqs_bonus"])

            # Rule 2: If stops are getting hit but price later reaches TP, widen stops
            # Approximate: check trades where outcome is LOSS_STOP and see if TP1 was reachable
            stop_losses = [t for t in trades if t.instrument == inst and t.outcome == "LOSS_STOP"]
            if len(stop_losses) >= 3:
                # Calculate average overshoot: how far past stop did price go before reversing?
                overshoots = []
                for t in stop_losses:
                    # Estimate: the risk was |entry - stop|, if price went to stop and
                    # then came back to reach TP, the overshoot is roughly the stop distance
                    risk = abs(t.entry_price - t.stop)
                    if risk > 0:
                        # Approximate overshoot as fraction of risk
                        overshoot = abs(t.exit_price - t.stop) / risk if t.exit_price != t.stop else 0
                        overshoots.append(overshoot)

                if overshoots:
                    avg_overshoot = np.mean(overshoots)
                    # If average overshoot is significant, widen stops
                    current_mult = adj.get("stop_multiplier", 2.0)
                    if avg_overshoot > 0.1 and g.win_rate < 0.50:
                        new_mult = min(3.0, current_mult + 0.25)
                        if new_mult != current_mult:
                            adj["stop_multiplier"] = round(new_mult, 2)
                            self._log.info("learner.stop_widen",
                                           instrument=inst,
                                           avg_overshoot=round(avg_overshoot, 3),
                                           new_multiplier=adj["stop_multiplier"])

            # Rule 4: If a regime type has <30% win rate, block trades in that regime
            blocked = adj.get("blocked_regimes", [])
            for key, grp in groups.items():
                if key.startswith(f"inst_regime:{inst}:") and grp.total_trades >= 5:
                    regime_name = key.split(":")[-1]
                    if grp.win_rate < 0.30 and regime_name not in blocked:
                        blocked.append(regime_name)
                        self._log.info("learner.regime_blocked",
                                       instrument=inst, regime=regime_name,
                                       win_rate=round(grp.win_rate, 3))
            adj["blocked_regimes"] = blocked

            self.adjustments.instruments[inst] = adj

    def _generate_session_adjustments(self, trades: list, groups: dict) -> None:
        """Generate per-session (kill zone) adjustments."""
        for key, g in groups.items():
            if not key.startswith("kz:"):
                continue
            kz_name = key.split(":")[1]

            session_adj = self.adjustments.sessions.get(kz_name, {})

            # Rule 3: If a specific kill zone has >60% win rate, give it a TQS bonus
            if g.total_trades >= 5 and g.win_rate > 0.60:
                current_bonus = session_adj.get("tqs_bonus", 0)
                if current_bonus < 10:  # Cap at +10
                    session_adj["tqs_bonus"] = current_bonus + 3
                    self._log.info("learner.session_bonus",
                                   kill_zone=kz_name,
                                   win_rate=round(g.win_rate, 3),
                                   tqs_bonus=session_adj["tqs_bonus"])

            session_adj["win_rate"] = round(g.win_rate, 3)
            session_adj["trades"] = g.total_trades
            self.adjustments.sessions[kz_name] = session_adj

    def _generate_global_adjustments(self, trades: list) -> None:
        """Generate global adjustments across all instruments."""
        if not trades:
            return

        wins = [t for t in trades if t.pnl > 0]
        losses = [t for t in trades if t.pnl <= 0]

        self.adjustments.global_adjustments = {
            "total_trades": len(trades),
            "win_rate": round(len(wins) / len(trades), 3) if trades else 0,
            "avg_win": round(float(np.mean([t.pnl for t in wins])), 2) if wins else 0,
            "avg_loss": round(float(np.mean([t.pnl for t in losses])), 2) if losses else 0,
            "total_pnl": round(sum(t.pnl for t in trades), 2),
        }

    def get_adjustments_dict(self) -> dict:
        """Return adjustments as a plain dict for the BacktestEngine."""
        return {
            "instruments": self.adjustments.instruments,
            "sessions": self.adjustments.sessions,
            "global_adjustments": self.adjustments.global_adjustments,
        }

    def _tune_config(self, config, trades: list, pass_num: int = 1) -> None:
        """Aggressively tune config parameters based on trade analysis between passes."""
        if not trades:
            return

        wins = [t for t in trades if t.pnl > 0]
        losses = [t for t in trades if t.pnl <= 0]
        wr = len(wins) / len(trades) if trades else 0
        stop_losses = [t for t in trades if t.outcome == "LOSS_STOP"]
        stop_pct = len(stop_losses) / len(trades) if trades else 0

        # Each pass tries a different strategy variation
        if pass_num == 2:
            # Pass 2: Tighten entry quality, widen stops
            config.premium_discount_long_max = 0.35
            config.premium_discount_short_min = 0.65
            config.stop_multiplier = min(3.0, config.stop_multiplier + 0.5)
            config.confluence_minimum = min(0.50, config.confluence_minimum + 0.10)

        elif pass_num == 3:
            # Pass 3: Maximize selectivity — only best setups
            config.premium_discount_long_max = 0.30
            config.premium_discount_short_min = 0.70
            config.require_kill_zone = True
            config.confluence_minimum = 0.45
            config.tp1_ratio = 1.5  # Easier TP

        elif pass_num == 4:
            # Pass 4: Wider stops + wider TPs, trade fewer but hold longer
            config.stop_multiplier = 2.5
            config.tp1_ratio = 3.0
            config.tp2_ratio = 4.5
            config.require_kill_zone = False
            config.premium_discount_long_max = 0.40
            config.confluence_minimum = 0.35

        elif pass_num == 5:
            # Pass 5: Use learnings from best previous pass + aggressive filtering
            if wr < 0.50:
                config.require_trending = True
                config.require_1h_structure = True
                config.premium_discount_long_max = 0.35
            if stop_pct > 0.40:
                config.stop_multiplier = min(3.0, config.stop_multiplier + 0.75)
            if wins and losses:
                avg_win = np.mean([t.pnl for t in wins])
                avg_loss = abs(np.mean([t.pnl for t in losses]))
                if avg_loss > 0 and avg_win / avg_loss < 1.0:
                    config.tp1_ratio = max(1.5, config.tp1_ratio - 0.5)  # Easier targets

    def learn_and_improve(self, bars: list, instrument: str, passes: int = 5,
                          base_config=None) -> dict:
        """Multi-pass learning: run backtest N times, improving each pass.

        Args:
            bars: 1-minute bars for the instrument.
            instrument: Instrument symbol.
            passes: Number of learning passes.
            base_config: Base BacktestConfig to start from.

        Returns:
            Dict with best_config, best_result, all_results, and final_adjustments.
        """
        from ghost.modules.m00_backtest.engine import BacktestEngine, BacktestConfig

        if base_config is None:
            base_config = BacktestConfig()

        # Load previous learnings and apply to base config
        self.load()
        self.apply_learnings_to_config(base_config, instrument)

        best_sharpe = -999.0
        best_wr = 0.0
        best_config = copy.deepcopy(base_config)
        best_result = None
        all_results = []
        current_adjustments = {}
        evolving_config = copy.deepcopy(base_config)

        for p in range(passes):
            self._log.info("learn_pass_start", pass_num=p + 1, total=passes)

            # Create engine with evolving config and learner adjustments
            config = copy.deepcopy(evolving_config)
            engine = BacktestEngine(config=config, learner_adjustments=current_adjustments)

            # Run backtest
            result = engine.run(bars, instrument)

            pass_info = {
                "pass": p + 1,
                "trades": result.total_trades,
                "win_rate": round(result.win_rate * 100, 1),
                "total_pnl": round(result.total_pnl, 2),
                "sharpe": round(result.sharpe_ratio, 2),
                "profit_factor": round(result.profit_factor, 2),
                "stop_mult": round(config.stop_multiplier, 2),
                "tp1_ratio": round(config.tp1_ratio, 2),
                "pd_long": round(config.premium_discount_long_max, 2),
                "pd_short": round(config.premium_discount_short_min, 2),
            }
            all_results.append(pass_info)

            self._log.info("learn_pass_result", **pass_info)

            # Record each pass to performance history
            self.record_run(instrument, result, config)

            # Track best using composite score: WR * trade_count + Sharpe
            if result.total_trades >= 3:
                score = result.win_rate * 100 + result.sharpe_ratio * 5
                best_score = best_wr * 100 + best_sharpe * 5
                if score > best_score:
                    best_sharpe = result.sharpe_ratio
                    best_wr = result.win_rate
                    best_config = copy.deepcopy(config)
                    best_result = result

            # Analyze trades and generate adjustments for next pass
            if result.trades:
                self.adjustments.pass_number = p + 1
                self.analyze(result.trades, instrument)
                current_adjustments = self.get_adjustments_dict()

                # Tune config parameters for next pass
                self._tune_config(evolving_config, result.trades, pass_num=p + 2)

        # Save final learnings (includes per-instrument params + performance history)
        self.save()

        return {
            "best_config": best_config,
            "best_result": best_result,
            "all_results": all_results,
            "final_adjustments": self.get_adjustments_dict(),
        }
